Add force opt, use .ut for root; Bump ut to 0.0.2

diff --git a/ut b/ut
--- a/ut
+++ b/ut
@@ -3,11 +3,10 @@
 utcalled=$_
 if [ $utcalled == $0 ]; then
 
-UT_VERSION="0.0.1"
-
 UTOPTHELP="--help"
 UTOPTVERSION="--version"
 UTOPTFAST="--fast"
+UTOPTFORCE="-f"
 UTOPTVERBOSE="-v"
 UTOPTINCLUDE="-I"
 UTOPTPATH="-C"
@@ -25,13 +24,15 @@ UTBIN=$0
 UTARG=$1
 
 if [ "x${UTARG}" = "xcomplete" ]; then
-    echo "$UTOPTHELP $UTOPTVERSION $UTOPTFAST $UTOPTVERBOSE $UTOPTINCLUDE $UTOPTPATH $UTINIT $UTHELP $UTVERSION $UTCLEAN $UTTEST $UTRETEST $UTWATCH"
+    echo "$UTOPTHELP $UTOPTVERSION $UTOPTFAST $UTOPTFORCE $UTOPTVERBOSE $UTOPTINCLUDE $UTOPTPATH $UTINIT $UTHELP $UTVERSION $UTCLEAN $UTTEST $UTRETEST $UTWATCH"
     exit 0
 fi
 
 UT=ut
 UTBINPATH=$(realpath `readlink ${UTBIN} || echo ${UTBIN}`)
 UTROOT=`dirname ${UTBINPATH}`
+UT_VERSION=`grep "define UT_VERSION" ${UTROOT}/ut.h|cut -d'"' -f2`
+
 
 UTMAKEFILE=${UTROOT}/Makefile
 
@@ -55,6 +56,10 @@ while true; do
         ;;
     ${UTOPTFAST}) :
         UT_FAST=1
+        shift
+        ;;
+    ${UTOPTFORCE}) :
+        UT_FORCE=1
         shift
         ;;
     ${UTOPTVERBOSE}) :
@@ -167,14 +172,22 @@ elif [ -n "${DO_VERSION}" ]; then
     exit 0
 fi
 
+DOTUT=".ut"
+UT_UT="${UT_PROJ}/${DOTUT}"
 UTMK="ut.mk"
-UT_MK="${UT_PROJ}/${UTMK}"
+UT_MK="${UT_UT}/${UTMK}"
+UTCACHE="cache"
+UT_CACHE="${UT_UT}/${UTCACHE}"
 
 if [ -n "${DO_INIT}" ]; then
-    if [ -f ${UT_MK} ]; then
-        echo "Error: UT_PROJ=${UT_PROJ} directory already points to an existing ut project!"
-        exit 1
+    if [ -d ${UT_UT} ]; then
+        if [ "x${UT_FORCE}" != "x1" ]; then
+            echo "Error: \`${UT} ${UTINIT}\` cannot be run on existing ut project. Use ${UTOPTFORCE} to force"
+            exit 1
+        fi
     fi
+    mkdir -p ${UT_UT}
+    rm -Rf ${UT_CACHE}
     echo "# ut project: \"${UT_PKG}\", from ut version ${UT_VERSION}" > ${UT_MK}
     echo "" >> ${UT_MK}
     if [ -n "${UT_INCLUDES}" ]; then
@@ -197,30 +210,32 @@ if [ -n "${DO_INIT}" ]; then
 fi
 
 #echo "TESTING IF UT_PROJ=${UT_PROJ} directory is valid.."
-if [ ! -f "${UT_MK}" ]; then
+if [ ! -d "${UT_UT}" ]; then
+    UT_PROJ0=${UT_PROJ}
     while true; do
-        if [ -f "${UT_PROJ}/${UTMK}" ]; then
+        if [ -d "${UT_PROJ0}/${DOTUT}" ]; then
             break
         fi
-        if [ "${UT_PROJ}" = "/" ]; then
-            echo "error: could not find \`${UTMK}\` in \`${UT_PROJ}\` or any parent directory"
+        if [ "${UT_PROJ0}" = "/" ]; then
+            echo "error: could not find \`${DOTUT}\` in \`${UT_PROJ}\` or any parent directory"
             exit 1
         fi
-        UT_PROJ=`dirname ${UT_PROJ}`
+        UT_PROJ0=`dirname ${UT_PROJ0}`
     done
+    UT_PROJ=`dirname ${UT_PROJ0}`
 fi
 
 #UTARGS="$*"
 
 if [ -n "${DO_CLEAN}" ]; then
-    UT_PROJ="${UT_PROJ}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" mrproper ${UTARGS}
+    UT_PROJ="${UT_PROJ}" UT_VERSION="${UT_VERSION}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" mrproper ${UTARGS}
 elif [ -n "${DO_TEST}" ]; then
-    UT_PROJ="${UT_PROJ}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" all ${UTARGS}
+    UT_PROJ="${UT_PROJ}" UT_VERSION="${UT_VERSION}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" all ${UTARGS}
 elif [ -n "${DO_RETEST}" ]; then
-    UT_PROJ="${UT_PROJ}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" mrproper ${UTARGS}
-    UT_PROJ="${UT_PROJ}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" all ${UTARGS}
+    UT_PROJ="${UT_PROJ}" UT_VERSION="${UT_VERSION}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" mrproper ${UTARGS}
+    UT_PROJ="${UT_PROJ}" UT_VERSION="${UT_VERSION}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" all ${UTARGS}
 elif [ -n "${DO_WATCH}" ]; then
-    UT_PROJ="${UT_PROJ}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" watch ${UTARGS}
+    UT_PROJ="${UT_PROJ}" UT_VERSION="${UT_VERSION}" UT_VERBOSE="${UT_VERBOSE}" UT_FAST="${UT_FAST}" make ${SILENCEMAKE} -C "${UT_PROJ}" -f "${UTMAKEFILE}" watch ${UTARGS}
 else
     echo "Error: Nothing done ?!"
     exit 1
